[package]
name = "seaorm-1"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "0.12", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros" ] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"